# start from base (3.7.1)

FROM ubuntu:18.04

LABEL maintainer="Padmapriya"

RUN apt-get update -y && \
    apt-get install -y python-pip python-dev 

# We copy just the requirements.txt first to leverage Docker cache

COPY ./scripts/requirements.txt /app/requirements.txt
COPY ./scripts/start_app.sh /app/start_app.sh 

WORKDIR /app

RUN pip install -r requirements.txt

COPY . /app

ENV DB_HOST=localhost
ENV DB_PORT=5432
ENV DB_NAME=postgres
ENV DB_USER=postgres
ENV DB_PASS=password
ENV BUCKET_NAME=er-public-assets
ENV PREFIX=analytics_assessment/

RUN chmod +x start_app.sh

RUN ./start_app.sh 