# start from base (3.7.1)

FROM ubuntu:18.04

LABEL maintainer="Padmapriya"

RUN apt-get update -y && \
    apt-get install -y python-pip python-dev 

# We copy just the requirements.txt first to leverage Docker cache

COPY ./script/requirements.txt /app/requirements.txt

WORKDIR /app

RUN pip install -r requirements.txt

COPY . /app

CMD [ "python", "/src/config.py" ]